main:
  - identifier: "home"
    name: "home"
    url: "/"
    weight: 1

  - identifier: "blog"
    name: "blog"
    url: "/blog"
    weight: 2

  - identifier: "about"
    url: "/about"
    name: "about"
    weight: 3

  - identifier: "tags"
    name: "Tags"
    url: "/tags"
    weight: 4

# Social Media Configuration
social:
  - identifier: "linkedin"
    name: "LinkedIn"
    url: "https://www.linkedin.com/in/nick-fisher-software/"
    weight: 1

  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/nfisher23"
    weight: 2
